on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 17 * * 5'
name: auto bump
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8, 10, 11, 12, 13]
    steps:
      - uses: actions/checkout@v1
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Execute tests
        run: npm run test
  autoBump:
    needs: tests
    name: 'Auto bump'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: merge develop into master
        run: git merge develop
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Create release
        run: npm run release
      - name: Push release to master
        run: git push origin master --follow-tags
