on:
  schedule:
    - cron: "45 0 * * 1-5"
jobs:
  release:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - run: git checkout develop && git pull
      - run: git checkout master && git pull
      - run: git merge develop    
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci --silent
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm run release
      - run: git push --follow-tags origin master
      - run: git checkout develop
      - run: git merge master
      - run: git push origin develop
