on: pull_request
name: Run Tests
jobs:
  runTests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12, 13]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with: 
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Execute tests
      run: npm cit
