name: Weekly Release
on:
  schedule:
    - cron: "00 10 * * 3"
  workflow_dispatch:
jobs:
  build-release:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run release script
        run: ./scripts/release.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - run: git checkout master
      - uses: actions/setup-node@v3.4.0
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - run: git checkout master
      - uses: actions/setup-node@v3.4.0
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@allcapsdev"
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  create-pr:
    name: Create PR on push to release
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - run: git checkout master
      - name: pull-request
        uses: repo-sync/pull-request@v2.6
        with:
          source_branch: "master"
          destination_branch: "develop"
          pr_title: "Weekly Release"
          pr_body: ":tada: *An automated PR*"
          pr_label: "autorebase"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
